DELETE http://localhost:3003/api/blogs/62ae11574f62475dac99b631
// add token after "bearer " below
// get token by sending request via login.rest
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImZvbyIsImlkIjoiNjJhZTBlZTEzMWNlNWIzMzczZGUyNGE4IiwiaWF0IjoxNjU1NTc2NjA2LCJleHAiOjE2NTU1ODAyMDZ9.FYi6wCS4ETVFY-1EL-i-fALTfMhIE0WnLu8ioSLQNUg