DELETE http://localhost:3003/api/blogs/62ae1a933bed5fa4162142aa
// add token after "bearer " below
// get token by sending request via login.rest
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImZvbyIsImlkIjoiNjJhZTBlZTEzMWNlNWIzMzczZGUyNGE4IiwiaWF0IjoxNjU1NTc3MTgzLCJleHAiOjE2NTU1ODA3ODN9.Cex7I4iERT2flm2w-EbDPCxARD8ixzXju7FaXrcDHqU